pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // XposedBridge API (unofficial mirror)
        maven { url 'https://api.xposed.info/' }
    }
}
rootProject.name = "guard-native"
