package com.ghost.assist.core;

// GENERATED by tools/gen_registry_fallback.py - DO NOT EDIT BY HAND.
// Source of truth: native_core/registry_8071.json
// To change a value: edit the json and re-run the generator.
// Variant: DEBUG (embedded literal fallbacks)
//
// C5a 归一: build-time DEBUG fallback for the Filter install-time anchors.
// Replaces the hand-written `BuildConfig.DEBUG ? "x" : ""` second copy so
// registry_8071.json is the single source. Release emits "" for every
// constant -> GuardRuntime strict mode stays fail-closed (no plaintext).
public final class RegistryFallback {
    private RegistryFallback() {}

    // -- conv.list --
    public static final String CONV_LIST__MVVMLIST_CLASS = "com.tencent.mm.plugin.mvvmlist.MvvmList";
    public static final String CONV_LIST__ADAPTER_CLASS = "kc5.v0";
    public static final String CONV_LIST__ITEM_CLASS = "kc5.y";
    public static final String CONV_LIST__L1_METHODS = "n,m";
    public static final String CONV_LIST__L2_METHOD = "s";
    public static final String CONV_LIST__CONTACT_FIELDS = "d,e,f,a,b,c";
    public static final String CONV_LIST__WXID_GETTERS = "C0,h1,j1,i1,k1,getUsername,getUserName";

    // -- moments.feed --
    public static final String MOMENTS_FEED__ITEM_FRIEND = "na4.b";
    public static final String MOMENTS_FEED__ITEM_PROMO = "la4.p";
    public static final String MOMENTS_FEED__ADAPTER_CLASS = "e2";
    public static final String MOMENTS_FEED__WXID_FIELD = "field_userName";
    public static final String MOMENTS_FEED__INNER_FIELD = "d";
    public static final String MOMENTS_FEED__SNS_GETTER = "h1";
    public static final String MOMENTS_FEED__LIKE_LIST = "LikeUserList";
    public static final String MOMENTS_FEED__COMMENT_LIST = "CommentUserList";
    public static final String MOMENTS_FEED__ACTOR_FIELD_NAMES = "d,f435583d,username,field_userName";

    // -- contact.address --
    public static final String CONTACT_ADDRESS__LIVE_LIST = "com.tencent.mm.ui.contact.address.AddressLiveList";
    public static final String CONTACT_ADDRESS__MVVMLIST_CLASS = "com.tencent.mm.plugin.mvvmlist.MvvmList";
    public static final String CONTACT_ADDRESS__ADAPTER_CLASS = "ik3.t0";
    public static final String CONTACT_ADDRESS__ITEM_CLASS = "fc5.g";
    public static final String CONTACT_ADDRESS__CONTACT_CLASS = "com.tencent.mm.storage.z3";
    public static final String CONTACT_ADDRESS__CONTACT_FIELD = "d";
    public static final String CONTACT_ADDRESS__TYPE_FIELD = "e";
    public static final String CONTACT_ADDRESS__WXID_GETTER = "c1";

    // -- search.gateway --
    public static final String SEARCH_GATEWAY__GATEWAY = "fts_result_view";
    public static final String SEARCH_GATEWAY__ADAPTER_FAMILY = "q2,f0";
    public static final String SEARCH_GATEWAY__RENDER_HOOK = "getView";
    public static final String SEARCH_GATEWAY__EXTRACTOR_PROFILE = "wechat8071_fts_mixed";
    public static final String SEARCH_GATEWAY__SCOPE = "result_render_only";
}
