package com.ghost.assist.core;

// GENERATED by tools/gen_registry_fallback.py - DO NOT EDIT BY HAND.
// Source of truth: native_core/registry_8071.json
// To change a value: edit the json and re-run the generator.
// Variant: RELEASE (empty stubs, fail-closed)
//
// C5a 归一: build-time DEBUG fallback for the Filter install-time anchors.
// Replaces the hand-written `BuildConfig.DEBUG ? "x" : ""` second copy so
// registry_8071.json is the single source. Release emits "" for every
// constant -> GuardRuntime strict mode stays fail-closed (no plaintext).
public final class RegistryFallback {
    private RegistryFallback() {}

    // -- conv.list --
    public static final String CONV_LIST__MVVMLIST_CLASS = "";
    public static final String CONV_LIST__ADAPTER_CLASS = "";
    public static final String CONV_LIST__ITEM_CLASS = "";
    public static final String CONV_LIST__L1_METHODS = "";
    public static final String CONV_LIST__L2_METHOD = "";
    public static final String CONV_LIST__CONTACT_FIELDS = "";
    public static final String CONV_LIST__WXID_GETTERS = "";

    // -- moments.feed --
    public static final String MOMENTS_FEED__ITEM_FRIEND = "";
    public static final String MOMENTS_FEED__ITEM_PROMO = "";
    public static final String MOMENTS_FEED__ADAPTER_CLASS = "";
    public static final String MOMENTS_FEED__WXID_FIELD = "";
    public static final String MOMENTS_FEED__INNER_FIELD = "";
    public static final String MOMENTS_FEED__SNS_GETTER = "";
    public static final String MOMENTS_FEED__LIKE_LIST = "";
    public static final String MOMENTS_FEED__COMMENT_LIST = "";
    public static final String MOMENTS_FEED__ACTOR_FIELD_NAMES = "";

    // -- contact.address --
    public static final String CONTACT_ADDRESS__LIVE_LIST = "";
    public static final String CONTACT_ADDRESS__MVVMLIST_CLASS = "";
    public static final String CONTACT_ADDRESS__ADAPTER_CLASS = "";
    public static final String CONTACT_ADDRESS__ITEM_CLASS = "";
    public static final String CONTACT_ADDRESS__CONTACT_CLASS = "";
    public static final String CONTACT_ADDRESS__CONTACT_FIELD = "";
    public static final String CONTACT_ADDRESS__TYPE_FIELD = "";
    public static final String CONTACT_ADDRESS__WXID_GETTER = "";

    // -- search.gateway --
    public static final String SEARCH_GATEWAY__GATEWAY = "";
    public static final String SEARCH_GATEWAY__ADAPTER_FAMILY = "";
    public static final String SEARCH_GATEWAY__RENDER_HOOK = "";
    public static final String SEARCH_GATEWAY__EXTRACTOR_PROFILE = "";
    public static final String SEARCH_GATEWAY__SCOPE = "";
}
