#!/usr/bin/env python3
"""C5a 归一: generate the DEBUG fallback anchors for the business Filters from
native_core/registry_8071.json instead of hand-copying them.

Why this exists
---------------
Each Filter used to carry a hand-written second copy of the obfuscated WeChat
anchors, e.g.

    private static String ADAPTER_CLASS_71 = BuildConfig.DEBUG ? "kc5.v0" : "";

The same name already lives in registry_8071.json, so the literal was a second,
drift-prone source. This script makes registry_8071.json the SINGLE source: it
emits one generated class per build variant -

    src/debug/java/com/ghost/assist/core/RegistryFallback.java   -> real literals
    src/release/java/com/ghost/assist/core/RegistryFallback.java -> "" for every
                                                                     constant

Each Filter then references RegistryFallback.<CONST> as the fallback it hands to
GuardRuntime.getRecipeOrFallback(). Behaviour is byte-for-byte identical to the
old ternary:
  * debug  -> embedded literal (registry miss keeps old behaviour)
  * release-> "" (GuardRuntime strict mode returns "" regardless; fail-closed)

Single source of truth = native_core/registry_8071.json. The two .java files are
build artifacts, NEVER hand-edited - change the json and re-run this script. The
field names are derived from the json keys, so the debug and release variants can
never drift apart.

Usage:
    python tools/gen_registry_fallback.py
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "native_core", "registry_8071.json")
PKG_PATH = os.path.join("com", "ghost", "assist", "core")
OUT_DEBUG = os.path.join(ROOT, "src", "debug", "java", PKG_PATH, "RegistryFallback.java")
OUT_RELEASE = os.path.join(ROOT, "src", "release", "java", PKG_PATH, "RegistryFallback.java")

PACKAGE = "com.ghost.assist.core"
CLASS = "RegistryFallback"

# Entries excluded from the Java fallback layer entirely (not even as "" stub).
# Rationale: a2.sig.official_der is the WeChat-official cert DER used by
# A2SignatureSpoof (Route B / D-018). A2SignatureSpoof reads the value from its
# own local final constant OFFICIAL_DER_HEX, so it never touches
# RegistryFallback. Letting the generator emit RegistryFallback.A2_SIG_*
# anyway would (a) leave dead code in release and (b) expose the public-cert
# DER in debug-variant Java -- both contradict the P_AntiBanGate worklog watch
# "A2 料只进 registry_pack (不进 Java fallback)".
SKIP_ENTRIES = {"a2.sig"}


def norm(token):
    """conv.list -> CONV_LIST ; mvvmlist_class -> MVVMLIST_CLASS"""
    return re.sub(r"[^A-Z0-9]", "_", token.upper())


def const_name(entry, key):
    return norm(entry) + "__" + norm(key)


def java_str(value):
    """Escape a python str into a Java double-quoted string body."""
    return value.replace("\\", "\\\\").replace('"', '\\"')


def collect_constants():
    with open(SRC, "r", encoding="utf-8") as f:
        data = json.load(f)
    entries = data.get("entries", {})
    consts = []  # list of (const_name, entry, key, value)
    seen = {}
    for entry, fields in entries.items():
        if not isinstance(fields, dict):
            continue
        if entry in SKIP_ENTRIES:
            continue
        for key, value in fields.items():
            if not isinstance(value, str):
                continue  # only string anchors get a fallback constant
            name = const_name(entry, key)
            if name in seen:
                raise SystemExit(
                    "ERROR: constant name collision %s (%s.%s vs %s)"
                    % (name, entry, key, seen[name])
                )
            seen[name] = "%s.%s" % (entry, key)
            consts.append((name, entry, key, value))
    return consts


def render(consts, debug):
    variant = "DEBUG (embedded literal fallbacks)" if debug else "RELEASE (empty stubs, fail-closed)"
    lines = []
    lines.append("package %s;" % PACKAGE)
    lines.append("")
    lines.append("// GENERATED by tools/gen_registry_fallback.py - DO NOT EDIT BY HAND.")
    lines.append("// Source of truth: native_core/registry_8071.json")
    lines.append("// To change a value: edit the json and re-run the generator.")
    lines.append("// Variant: %s" % variant)
    lines.append("//")
    lines.append("// C5a 归一: build-time DEBUG fallback for the Filter install-time anchors.")
    lines.append("// Replaces the hand-written `BuildConfig.DEBUG ? \"x\" : \"\"` second copy so")
    lines.append("// registry_8071.json is the single source. Release emits \"\" for every")
    lines.append("// constant -> GuardRuntime strict mode stays fail-closed (no plaintext).")
    lines.append("public final class %s {" % CLASS)
    lines.append("    private %s() {}" % CLASS)
    last_entry = None
    for name, entry, key, value in consts:
        if entry != last_entry:
            lines.append("")
            lines.append("    // -- %s --" % entry)
            last_entry = entry
        body = java_str(value) if debug else ""
        lines.append('    public static final String %s = "%s";' % (name, body))
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote", os.path.relpath(path, ROOT))


def main():
    consts = collect_constants()
    write(OUT_DEBUG, render(consts, debug=True))
    write(OUT_RELEASE, render(consts, debug=False))
    print("constants:", len(consts))
    by_entry = {}
    for _, entry, _, _ in consts:
        by_entry[entry] = by_entry.get(entry, 0) + 1
    for entry, n in by_entry.items():
        print("  %-18s %d" % (entry, n))


if __name__ == "__main__":
    main()
