#!/usr/bin/env python3
"""Phase 1C: encrypt native_core/registry_8071.json into an AES-GCM blob and
emit a generated C include (native_core/src/registry_cipher.inc) consumed by
registry_loader.cpp.

Single source of truth = registry_8071.json. Re-run this after editing it; the
.inc is a build artifact, never hand-edited (kills the plaintext/embedded drift).

Phase 1D-local: the AES key is NO LONGER emitted into the .inc. It is DERIVED
from scattered in-SO segments via derive_registry_key() below, which MUST stay
byte-for-byte identical to guard::derive_registry_key() in
native_core/src/config_crypto.cpp. The nonce is randomized per build (stored in
the .inc) to avoid GCM nonce reuse across builds.

A-step2 (anti-repackage): the derivation also folds in the module signing-cert
SHA-256 (_CERT_SHA256 below). At runtime Java reads the installed module's cert
and pushes it via NativeBridge.setBindingMaterial(); a re-signed / repackaged
APK has a different cert → wrong key → scatter. _CERT_SHA256 MUST equal the
fixed keystore's cert SHA-256. Regenerate it with:
    keytool -list -v -keystore signing/guard-native-debug.keystore \
        -storepass android -alias androiddebugkey   (read the SHA256: line)

Phase 1D-server (later) folds server-derived key material into the derivation
(skill: server material must participate in final key derivation; no server
material → no real registry). Local material only raises the static-analysis bar.
"""
import json
import os

try:
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM
except ImportError:
    print("ERROR: pip install cryptography")
    raise SystemExit(1)

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "native_core", "registry_8071.json")
OUT = os.path.join(ROOT, "native_core", "src", "registry_cipher.inc")

# Phase 1D-local: scattered key segments + non-linear mix. MUST match
# guard::derive_registry_key() in native_core/src/config_crypto.cpp byte-for-byte.
_SEG_A = bytes([
    0x3f, 0xa1, 0x08, 0xd4, 0x77, 0x1c, 0xe9, 0x52,
    0x8b, 0x60, 0xbd, 0x14, 0xc6, 0x2a, 0x9f, 0x73,
])
_SEG_B = bytes([
    0x5e, 0x02, 0xab, 0x6d, 0xf1, 0x37, 0x80, 0xc4,
    0x19, 0xae, 0x4b, 0xd2, 0x66, 0x8f, 0x33, 0xe7,
])
_SEG_C = bytes([
    0x11, 0x9c, 0x4d, 0x70, 0x23, 0xba, 0x5f, 0x06,
    0xe1, 0x38, 0x7a, 0xcd, 0x90, 0x42, 0xfb, 0x85,
])

# A-step2 binding material = fixed keystore cert SHA-256 (signing/guard-native-
# debug.keystore, alias androiddebugkey). Runtime Java pushes the installed
# module's cert SHA-256 via setBindingMaterial(); must equal this for the
# registry to decrypt. See module docstring for the keytool regen command.
_CERT_SHA256 = bytes([
    0xca, 0x42, 0x1e, 0xc3, 0xa3, 0x37, 0x08, 0xce,
    0xb3, 0xf7, 0x0c, 0x37, 0xf4, 0x61, 0x67, 0x51,
    0x09, 0x47, 0x36, 0xc4, 0x96, 0xfe, 0x21, 0xb3,
    0xb0, 0xe2, 0xce, 0xa4, 0x80, 0xcd, 0xb6, 0xa0,
])


def _rotl8(x, r):
    r &= 7
    if r == 0:
        return x
    return ((x << r) | (x >> (8 - r))) & 0xff


def derive_registry_key():
    out = bytearray(16)
    blen = len(_CERT_SHA256)
    for i in range(16):
        t = _SEG_A[i] ^ _SEG_B[(i * 5 + 3) & 15]
        t = _rotl8(t, (i % 7) + 1)
        t ^= _SEG_C[i]
        t = (t + i * 37) & 0xff
        if blen > 0:
            t ^= _CERT_SHA256[(i * 2) % blen]
            t = _rotl8(t, _CERT_SHA256[(i * 2 + 1) % blen] & 7)
            t ^= _CERT_SHA256[(i + 7) % blen]
        out[i] = t
    return bytes(out)


key = derive_registry_key()
nonce = os.urandom(12)  # random per build → no GCM nonce reuse across builds

with open(SRC, "r", encoding="utf-8") as f:
    data = json.load(f)

# Strip top-level documentation keys (leading underscore) and minify.
data = {k: v for k, v in data.items() if not k.startswith("_")}
pt = json.dumps(data, separators=(",", ":"), ensure_ascii=False).encode("utf-8")

blob = AESGCM(key).encrypt(nonce, pt, None)
ct, tag = blob[:-16], blob[-16:]


def carr(name, b):
    body = ", ".join("0x%02x" % x for x in b)
    return "constexpr uint8_t %s[] = { %s };\n" % (name, body)


lines = [
    "// GENERATED by tools/gen_registry_cipher.py - DO NOT EDIT BY HAND.\n",
    "// Source of truth: native_core/registry_8071.json\n",
    "// Phase 1D-local: NO key constant here. The AES key is derived in-SO by\n",
    "// guard::derive_registry_key() (config_crypto.cpp). Nonce is random per build.\n",
    carr("kRegistryNonce", nonce),
    carr("kRegistryCipher", ct),
    carr("kRegistryTag", tag),
]
with open(OUT, "w", encoding="utf-8") as f:
    f.writelines(lines)

print("wrote", OUT)
print("pt_len", len(pt), "ct_len", len(ct))
print("schema entries:", list(data.get("entries", {}).keys()))
