#!/usr/bin/env python3
"""Emit native_core/src/kdf_vectors.inc — the KDF self-test vectors.

Purpose (F-31 guard)
--------------------
guard::derive_registry_key() / guard::derive_bootstrap_key() (C++, in
native_core/src/config_crypto.cpp) MUST stay byte-for-byte identical to the
Python side in tools/kdf_common.py. One byte off = 正版机 registry 散沙, silent
(no crash, no error). This script pins the Python output for a FIXED input matrix
into a generated C header; guard::kdf_self_test() (GUARD_DEV_SELFTEST only) derives the
same inputs at runtime and asserts equality, so any drift fails the build-time
gate (tools/run_native_tests.ps1) instead of shipping silently.

Single source of truth = tools/kdf_common.py (imported below — NOT re-copied).

Re-run after ANY change to the KDF: python tools/gen_kdf_vectors.py
"""
import os

import kdf_common as kc

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "native_core", "src", "kdf_vectors.inc")

# Fixed self-test inputs. The binding is the real signing-cert SHA-256 (the live
# A-step2 path), so kKdfVecRegistryCertOnly is the actual cert-only registry key.
# The seed is a fixed arbitrary 32-byte value purely to exercise the S_rel fold's
# index math (the real S_rel is server-side and per-release, never embedded).
TEST_BINDING = kc.CERT_SHA256
TEST_SEED = bytes((0xA0 + i) & 0xff for i in range(32))

VEC_REGISTRY_CERT_ONLY = kc.derive_registry_key(TEST_BINDING, b"")
VEC_REGISTRY_CERT_SEED = kc.derive_registry_key(TEST_BINDING, TEST_SEED)
VEC_BOOTSTRAP = kc.derive_bootstrap_key(TEST_BINDING)

# Domain separation invariant the C++ side also asserts: the registry cert-only
# key must differ from the bootstrap key (same binding, no seed). Fail loudly here
# too so a botched DOM tag can't even generate a "passing" vector file.
if VEC_REGISTRY_CERT_ONLY == VEC_BOOTSTRAP:
    raise SystemExit("ERROR: domain separation broken — registry key == bootstrap key")


def carr(name, b):
    body = ", ".join("0x%02x" % x for x in b)
    return "constexpr uint8_t %s[%d] = { %s };\n" % (name, len(b), body)


lines = [
    "// GENERATED by tools/gen_kdf_vectors.py - DO NOT EDIT BY HAND.\n",
    "// Source of truth: tools/kdf_common.py (mirrors guard::derive_* in config_crypto.cpp).\n",
    "// KDF self-test vectors: fixed (binding, seed) -> expected derive_* output.\n",
    "// Consumed by guard::kdf_self_test() (GUARD_DEV_SELFTEST only) to catch C++/Python\n",
    "// derive drift at build time (tools/run_native_tests.ps1). Re-run the generator\n",
    "// after ANY KDF change: python tools/gen_kdf_vectors.py\n",
    carr("kKdfTestBinding", TEST_BINDING),
    carr("kKdfTestSeed", TEST_SEED),
    carr("kKdfVecRegistryCertOnly", VEC_REGISTRY_CERT_ONLY),
    carr("kKdfVecRegistryCertSeed", VEC_REGISTRY_CERT_SEED),
    carr("kKdfVecBootstrap", VEC_BOOTSTRAP),
]

with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.writelines(lines)

print("wrote", os.path.relpath(OUT, ROOT))
print("reg_certonly", VEC_REGISTRY_CERT_ONLY.hex())
print("reg_certseed", VEC_REGISTRY_CERT_SEED.hex())
print("bootstrap   ", VEC_BOOTSTRAP.hex())
