#!/usr/bin/env python3
"""C2: encrypt native_core/bootstrap_endpoints.json into an AES-GCM blob and emit
native_core/src/bootstrap_cipher.inc, consumed by registry_loader.cpp.

Single source of truth = bootstrap_endpoints.json. Re-run after editing it; the
.inc is a build artifact, never hand-edited.

Key = derive_bootstrap_key() below, which MUST stay byte-for-byte identical to
guard::derive_bootstrap_key() in native_core/src/config_crypto.cpp.

Difference vs gen_registry_cipher.py::derive_registry_key():
  - The bootstrap key NEVER folds the server seed (S_rel). The endpoints must
    decrypt cert-only so the client can reach the server BEFORE any handshake.
    If they were gated behind the server seed (prod_server_lock), you would need
    the server to get the seed but need the endpoint to reach the server =
    deadlock. So the bootstrap blob stays cert-only forever.
  - A fixed 16-byte domain-separation tag (_DOM) is folded in so the bootstrap
    key differs from the registry cert-only key (cracking one blob's key != the
    other).

The cert binding (_CERT_SHA256) is the SAME fixed keystore cert SHA-256 as
gen_registry_cipher.py (anti-repackage: re-signed APK -> wrong key -> scatter).
"""
import base64
import json
import os

try:
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM
except ImportError:
    print("ERROR: pip install cryptography")
    raise SystemExit(1)

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "native_core", "bootstrap_endpoints.json")
OUT = os.path.join(ROOT, "native_core", "src", "bootstrap_cipher.inc")

# The scattered segments, domain tag, cert binding, rotl8 and derive routine live
# in ONE place now — tools/kdf_common.py — shared with gen_registry_cipher.py and
# the KDF self-test vectors. kdf_common.derive_bootstrap_key MUST stay
# byte-for-byte identical to guard::derive_bootstrap_key() in config_crypto.cpp.
from kdf_common import CERT_SHA256, derive_bootstrap_key as _kdf_derive_bootstrap_key


def derive_bootstrap_key():
    """Cert-only bootstrap key (no server seed, + domain tag). Mirrors
    guard::derive_bootstrap_key() via the shared kdf_common routine."""
    return _kdf_derive_bootstrap_key(CERT_SHA256)


def carr(name, b):
    body = ", ".join("0x%02x" % x for x in b)
    return "constexpr uint8_t %s[] = { %s };\n" % (name, body)


key = derive_bootstrap_key()
nonce = os.urandom(12)  # random per build -> no GCM nonce reuse

with open(SRC, "r", encoding="utf-8") as f:
    data = json.load(f)

# Strip documentation keys (leading underscore) and minify.
data = {k: v for k, v in data.items() if not k.startswith("_")}
pt = json.dumps(data, separators=(",", ":"), ensure_ascii=False).encode("utf-8")

blob = AESGCM(key).encrypt(nonce, pt, None)
ct, tag = blob[:-16], blob[-16:]

lines = [
    "// GENERATED by tools/gen_bootstrap_cipher.py - DO NOT EDIT BY HAND.\n",
    "// Source of truth: native_core/bootstrap_endpoints.json\n",
    "// C2 cert-only bootstrap: key = guard::derive_bootstrap_key() (no server\n",
    "// seed, + domain tag). Nonce random per build. Decrypts the AUTH server\n",
    "// endpoint list before any server handshake (avoids prod_server_lock deadlock).\n",
    carr("kBootstrapNonce", nonce),
    carr("kBootstrapCipher", ct),
    carr("kBootstrapTag", tag),
]
with open(OUT, "w", encoding="utf-8") as f:
    f.writelines(lines)
print("wrote", OUT)
print("pt_len", len(pt), "ct_len", len(ct))
print("endpoints:", list(data.get("entries", {}).get("net.endpoint", {}).keys()))
