#!/usr/bin/env python3
"""C2: encrypt native_core/bootstrap_endpoints.json into an AES-GCM blob and emit
native_core/src/bootstrap_cipher.inc, consumed by registry_loader.cpp.

Single source of truth = bootstrap_endpoints.json. Re-run after editing it; the
.inc is a build artifact, never hand-edited.

Key = derive_bootstrap_key() below, which MUST stay byte-for-byte identical to
guard::derive_bootstrap_key() in native_core/src/config_crypto.cpp.

Difference vs gen_registry_cipher.py::derive_registry_key():
  - The bootstrap key NEVER folds the server seed (S_rel). The endpoints must
    decrypt cert-only so the client can reach the server BEFORE any handshake.
    If they were gated behind the server seed (prod_server_lock), you would need
    the server to get the seed but need the endpoint to reach the server =
    deadlock. So the bootstrap blob stays cert-only forever.
  - A fixed 16-byte domain-separation tag (_DOM) is folded in so the bootstrap
    key differs from the registry cert-only key (cracking one blob's key != the
    other).

The cert binding (_CERT_SHA256) is the SAME fixed keystore cert SHA-256 as
gen_registry_cipher.py (anti-repackage: re-signed APK -> wrong key -> scatter).
"""
import base64
import json
import os

try:
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM
except ImportError:
    print("ERROR: pip install cryptography")
    raise SystemExit(1)

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "native_core", "bootstrap_endpoints.json")
OUT = os.path.join(ROOT, "native_core", "src", "bootstrap_cipher.inc")

# MUST match config_crypto.cpp seg_a/seg_b/seg_c (shared with registry key).
_SEG_A = bytes([
    0x3f, 0xa1, 0x08, 0xd4, 0x77, 0x1c, 0xe9, 0x52,
    0x8b, 0x60, 0xbd, 0x14, 0xc6, 0x2a, 0x9f, 0x73,
])
_SEG_B = bytes([
    0x5e, 0x02, 0xab, 0x6d, 0xf1, 0x37, 0x80, 0xc4,
    0x19, 0xae, 0x4b, 0xd2, 0x66, 0x8f, 0x33, 0xe7,
])
_SEG_C = bytes([
    0x11, 0x9c, 0x4d, 0x70, 0x23, 0xba, 0x5f, 0x06,
    0xe1, 0x38, 0x7a, 0xcd, 0x90, 0x42, 0xfb, 0x85,
])

# Domain-separation tag — bootstrap-only. MUST match config_crypto.cpp _DOM.
_DOM = bytes([
    0x9a, 0x47, 0xe1, 0x05, 0x3c, 0xb8, 0x6f, 0xd2,
    0x14, 0x8e, 0x7b, 0xa3, 0x50, 0xc9, 0x2d, 0xf6,
])

# Fixed keystore cert SHA-256 (signing/guard-native-debug.keystore, alias
# androiddebugkey). MUST match gen_registry_cipher.py::_CERT_SHA256 and the
# runtime cert pushed via NativeBridge.setBindingMaterial().
_CERT_SHA256 = bytes([
    0xca, 0x42, 0x1e, 0xc3, 0xa3, 0x37, 0x08, 0xce,
    0xb3, 0xf7, 0x0c, 0x37, 0xf4, 0x61, 0x67, 0x51,
    0x09, 0x47, 0x36, 0xc4, 0x96, 0xfe, 0x21, 0xb3,
    0xb0, 0xe2, 0xce, 0xa4, 0x80, 0xcd, 0xb6, 0xa0,
])


def _rotl8(x, r):
    r &= 7
    if r == 0:
        return x
    return ((x << r) | (x >> (8 - r))) & 0xff


def derive_bootstrap_key():
    """Mirror guard::derive_bootstrap_key() in config_crypto.cpp byte-for-byte."""
    out = bytearray(16)
    blen = len(_CERT_SHA256)
    for i in range(16):
        t = _SEG_A[i] ^ _SEG_B[(i * 5 + 3) & 15]
        t = _rotl8(t, (i % 7) + 1)
        t ^= _SEG_C[i]
        t = (t + i * 37) & 0xff
        if blen > 0:
            t ^= _CERT_SHA256[(i * 2) % blen]
            t = _rotl8(t, _CERT_SHA256[(i * 2 + 1) % blen] & 7)
            t ^= _CERT_SHA256[(i + 7) % blen]
        # Domain separation (instead of the server seed used by the registry key).
        t ^= _DOM[i]
        t = _rotl8(t, _DOM[(i * 7 + 1) & 15] & 7)
        out[i] = t
    return bytes(out)


def carr(name, b):
    body = ", ".join("0x%02x" % x for x in b)
    return "constexpr uint8_t %s[] = { %s };\n" % (name, body)


key = derive_bootstrap_key()
nonce = os.urandom(12)  # random per build -> no GCM nonce reuse

with open(SRC, "r", encoding="utf-8") as f:
    data = json.load(f)

# Strip documentation keys (leading underscore) and minify.
data = {k: v for k, v in data.items() if not k.startswith("_")}
pt = json.dumps(data, separators=(",", ":"), ensure_ascii=False).encode("utf-8")

blob = AESGCM(key).encrypt(nonce, pt, None)
ct, tag = blob[:-16], blob[-16:]

lines = [
    "// GENERATED by tools/gen_bootstrap_cipher.py - DO NOT EDIT BY HAND.\n",
    "// Source of truth: native_core/bootstrap_endpoints.json\n",
    "// C2 cert-only bootstrap: key = guard::derive_bootstrap_key() (no server\n",
    "// seed, + domain tag). Nonce random per build. Decrypts the AUTH server\n",
    "// endpoint list before any server handshake (avoids prod_server_lock deadlock).\n",
    carr("kBootstrapNonce", nonce),
    carr("kBootstrapCipher", ct),
    carr("kBootstrapTag", tag),
]
with open(OUT, "w", encoding="utf-8") as f:
    f.writelines(lines)
print("wrote", OUT)
print("pt_len", len(pt), "ct_len", len(ct))
print("endpoints:", list(data.get("entries", {}).get("net.endpoint", {}).keys()))
