#include "../native_core/include/guard_core.h"
#include <cstdint>
#include <cstdio>

// Host-side crypto test harness. Compile & run on the dev machine (no device)
// to catch encryption-chain drift at build time instead of only at install
// time via logcat PHASE*_VERIFY.
//
// Coverage:
//   1. decrypt_config_self_test()  — AES/GCM primitives, tamper-must-scatter.
//   2. registry_self_test()        — embedded registry decrypts + anchors match.
//
// IMPORTANT (why set_binding_material first):
//   registry_8071.json's cipher (registry_cipher.inc) is generated by
//   tools/gen_registry_cipher.py with the signing-cert SHA-256 folded into the
//   key (Python's _CERT_SHA256, blen=32 → ALWAYS folded). guard::
//   derive_registry_key() only folds the cert when g_binding_len > 0. A
//   standalone test process never runs ModuleMain.bindSigningCert(), so without
//   the call below g_binding_len == 0 → the SO-side key omits the cert fold →
//   key mismatch → scatter → registry_self_test() would fail spuriously.
//   So we push the SAME 32 bytes here to mirror the build-time derivation.
//
//   Server seed S_rel is intentionally NOT set: the current registry_cipher.inc
//   is cert-only (S3a not done, see PROTECTION_MAP §10.6). Folding a server seed
//   here would diverge from the build → scatter.
//
// kCertSha256 MUST stay byte-for-byte identical to _CERT_SHA256 in
// tools/gen_registry_cipher.py. If the signing keystore changes, regenerate
// both (keytool) together.
static const uint8_t kCertSha256[32] = {
    0xca, 0x42, 0x1e, 0xc3, 0xa3, 0x37, 0x08, 0xce,
    0xb3, 0xf7, 0x0c, 0x37, 0xf4, 0x61, 0x67, 0x51,
    0x09, 0x47, 0x36, 0xc4, 0x96, 0xfe, 0x21, 0xb3,
    0xb0, 0xe2, 0xce, 0xa4, 0x80, 0xcd, 0xb6, 0xa0};

int main() {
    bool crypto_ok = guard::decrypt_config_self_test();
    printf("decrypt_config_self_test=%s\n", crypto_ok ? "PASS" : "FAIL");

    // Mirror build-time key derivation (cert-only, no server seed).
    guard::clear_server_seed();
    guard::set_binding_material(kCertSha256, sizeof(kCertSha256));

    bool registry_ok = guard::registry_self_test();
    printf("registry_self_test=%s\n", registry_ok ? "PASS" : "FAIL");
    printf("registry_summary=%s\n", guard::registry_dump_summary().c_str());

    std::string reg = guard::decrypt_config_test_registry();
    printf("registry=%s\n", reg.c_str());

    bool all_ok = crypto_ok && registry_ok;
    printf("ALL=%s\n", all_ok ? "PASS" : "FAIL");
    return all_ok ? 0 : 1;
}
